# Generated by Django 3.0.8 on 2020-08-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email-id')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='College')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
