# Generated by Django 3.0.8 on 2020-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.CharField(default='nothing', max_length=200, null=True),
        ),
    ]
