# Generated by Django 3.0.8 on 2020-09-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='stream',
            new_name='stream_name',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='stream',
            new_name='stream_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stream',
            new_name='stream_name',
        ),
    ]
