# Generated by Django 3.0.8 on 2020-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200826_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='stream',
            field=models.ManyToManyField(to='college.Stream'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.CharField(default='STREAM', max_length=200, null=True),
        ),
    ]
