# Generated by Django 3.0.8 on 2020-09-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20200901_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Stream'),
        ),
    ]
